- name: Run tasks from java
  ansible.builtin.include_role:
    name: common
    tasks_from: java

- name: Install mysql
  ansible.builtin.dnf:
    name:
      - mysql
      - python3-mysqlclient
    state: latest


- name: LoadSchema
  ansible.builtin.shell:mysql-dev.devopsazurepractice.online



#- name: Load schema
#  community.mysql.mysql_db:
#    state: import
#    name: all
#    target: /app/db/schema.sql
#    login_host: mysql-dev.devopsazurepractice.online
#    login_user: root
#    login_password: Roboshop@1
#
#- name: Load app-user
#  community.mysql.mysql_db:
#    state: import
#    name: all
#    target: /app/db/app-user.sql
#    login_host: mysql-dev.devopsazurepractice.online
#    login_user: root
#    login_password: Roboshop@1
#
#- name: Load master-data
#  community.mysql.mysql_db:
#    state: import
#    name: all
#    target: /app/db/master-data.sql
#    login_host: mysql-dev.devopsazurepractice.online
#    login_user: root
#    login_password: Roboshop@1

