- name: Run tasks from java
  ansible.builtin.include_role:
    name: common
    tasks_from: java

- name: Install mysql
  ansible.builtin.dnf:
    name: mysql
    state: latest

- name: Load schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/db/schema.sql
    local_host: 10.0.0.12
    login_user: root
    login_password: roboshop@1

- name: Load app-user
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/db/app-user.sql
    local_host: 10.0.0.12
    login_user: root
    login_password: roboshop@1

- name: Load master-data
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/db/master-data.sql
    local_host: 10.0.0.12
    login_user: root
    login_password: roboshop@1

