dev:
	git pull
	ansible-playbook -i $(app_name)-dev.devopsazurepractice.online, -e ansible_user=harsha -e ansible_password=Harsha@123456 -e ENV=dev -e app_name=$(app_name) roboshop.yml

prod:
	git pull
	ansible-playbook -i $(app_name)-dev.devopsazurepractice.online, -e ansible_user=harsha -e ansible_password=Harsha@123456 -e ENV=prod -e app_name=$(app_name) roboshop.yml