
- name: Install sql
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: enable mysqld
  ansible.builtin.systemd_service:
    state: restarted
    name: mysqld
    enabled: true

- name: set password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1