- name: Install golang
  ansible.builtin.dnf:
    name: golang
    state: latest


- name: Initialize Go module
  command: go mod init {{ comp_name }}
  args:
    chdir: /app

- name: Get dependencies
  command: go get
  args:
    chdir: /app

- name: Build the Go project
  command: go build

- name: Run tasks from prereq
  ansible.builtin.include_role:
    name: common
    tasks_from: prereq



- name: Run tasks from prereq
  ansible.builtin.include_role:
    name: common
    tasks_from: systemsetup