

- name: Add roboshopuser
  ansible.builtin.user:
    name: roboshop

- name: Recursively remove directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Unarchive a file that needs to be downloaded
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ comp_name }}-v3.zip
    dest: /app
    remote_src: yes