- name: Find all processes running as roboshop
  ansible.builtin.shell: "ps -u roboshop -o pid="
    register: roboshop_processes
    ignore_errors: true

- name: Kill any running processes for roboshop user
  ansible.builtin.shell: "kill -9 {{ item }}"
      with_items: "{{ roboshop_processes.stdout_lines }}"
      when: roboshop_processes.stdout_lines | length > 0
      ignore_errors: true

    - name: Remove roboshop user and home directory
      ansible.builtin.user:
        name: roboshop
        state: absent
        remove: yes

- name: Add roboshopuser
  ansible.builtin.user:
    name: roboshop

- name: Recursively remove directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Remove application zip file
  ansible.builtin.file:
      path: "{{ comp_name }}.zip"
      state: absent

- name: Unarchive a file that needs to be downloaded
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{ comp_name }}-v3.zip
    dest: /app
    remote_src: yes