- name: Install python
  ansible.builtin.dnf:
    name:
      - gcc
      - python3
      - python3-devel
      - python3-mysqlclient
    state: latest

- name: Run tasks from prereq
  ansible.builtin.include_role:
    name: common
    tasks_from: prereq

- name: Install specified python requirements
  ansible.builtin.pip:
    requirements: /app/requirements.txt
    executable: pip3

- name: Run tasks from systemsetup
  ansible.builtin.include_role:
    name: common
    tasks_from: systemsetup