

- name: Copy file repo
  ansible.builtin.copy:
    src: "{{ comp_name }}.service"
    dest: /etc/systemd/system/{{comp_name}}.service

- name: Reload
  ansible.builtin.systemd_service:
    name: "{{ comp_name}}"
    state: restarted
    enabled: true
    daemon_reload: true



